export const profileCandidateFixture = {
  id: "candidate-a",
  name: "Jordan Rivera",
  initials: "JR",
  party: "democratic",
  partyLabel: "Democratic ballot",
  office: "Example statewide office",
  role: "Current officeholder",
  locality: "Example, Massachusetts",
  summary: "A fictional fixture used to exercise sourced biography, career, election, and synthesis states without publishing a claim about a real candidate.",
  evidence: {
    ballot: "verified",
    record: "available",
    finance: "partial",
    positions: "researching",
  },
};

export const profileFixture = {
  id: "profile-candidate-a",
  checkedAt: "2026-08-24",
  photo: {
    url: "https://example.test/candidate-a.jpg",
    alt: "Jordan Rivera",
    verificationStatus: "verified",
    rightsStatus: "publishable",
    sourceId: "official-biography",
    checkedAt: "2026-08-24",
  },
  links: [
    {
      id: "official-office",
      label: "Official office page",
      url: "https://example.test/office",
      kind: "official-government",
      sourceId: "official-biography",
    },
    {
      id: "campaign-site",
      label: "Campaign website",
      url: "https://example.test/campaign",
      kind: "campaign-controlled",
      sourceId: "campaign-profile",
    },
  ],
  facts: [
    {
      id: "current-office",
      label: "Current office",
      value: "Example office",
      detail: "Term began January 2023",
      status: "available",
      sourceIds: ["official-biography"],
    },
    {
      id: "public-service-start",
      label: "Public record begins",
      value: "2013",
      detail: "Earliest reviewed role in this profile",
      status: "available",
      sourceIds: ["official-biography"],
    },
    {
      id: "election-history",
      label: "Elections in dataset",
      value: "3",
      detail: "Primary and general contests are labeled separately",
      status: "partial",
      sourceIds: ["election-results"],
    },
    {
      id: "position-coverage",
      label: "Position research",
      value: "In progress",
      detail: "Unknown positions are not inferred",
      status: "researching",
      sourceIds: [],
    },
  ],
  timeline: [
    {
      id: "municipal-role",
      title: "Municipal role",
      organization: "Example municipality",
      startDate: "2013-01-01",
      endDate: "2018-12-31",
      description: "Dates come from the official biography fixture.",
      evidenceKind: "official-government",
      status: "available",
      sourceIds: ["official-biography"],
    },
    {
      id: "legislative-role",
      title: "Legislative role",
      organization: "Example legislature",
      startDate: "2019-01-02",
      endDate: "2022-12-31",
      description: "A distinct public-service interval.",
      evidenceKind: "legislative-record",
      status: "available",
      sourceIds: ["legislative-directory"],
    },
    {
      id: "current-role",
      title: "Current office",
      organization: "Example commonwealth office",
      startDate: "2023-01-04",
      endDate: null,
      description: "The open interval is clipped to the profile review date.",
      evidenceKind: "official-government",
      status: "available",
      sourceIds: ["official-biography"],
    },
  ],
  elections: [
    {
      id: "election-2018",
      date: "2018-11-06",
      office: "Example municipal office",
      electionType: "General election",
      jurisdiction: "Example municipality",
      candidateVotes: 8_240,
      totalVotes: 18_100,
      result: "Elected",
      status: "available",
      sourceIds: ["election-results"],
    },
    {
      id: "election-2022-primary",
      date: "2022-09-06",
      office: "Example statewide office",
      electionType: "Party primary",
      jurisdiction: "Massachusetts",
      candidateVotes: 318_300,
      totalVotes: 606_400,
      result: "Nominated",
      status: "available",
      sourceIds: ["election-results"],
    },
    {
      id: "election-2022-general",
      date: "2022-11-08",
      office: "Example statewide office",
      electionType: "General election",
      jurisdiction: "Massachusetts",
      candidateVotes: 1_209_900,
      totalVotes: 2_126_700,
      result: "Elected",
      status: "available",
      sourceIds: ["election-results"],
    },
  ],
  evidence: [
    { id: "ballot", status: "verified", detail: "Roster identity reviewed", sourceIds: ["election-results"] },
    { id: "biography", status: "available", detail: "Three sourced roles", sourceIds: ["official-biography", "legislative-directory"] },
    { id: "elections", status: "available", detail: "Three result records", sourceIds: ["election-results"] },
    { id: "finance", status: "partial", detail: "Current-cycle totals available", sourceIds: [] },
    { id: "positions", status: "researching", detail: "Claims and actions not yet synthesized", sourceIds: [] },
  ],
  synthesis: {
    title: "Record orientation",
    text: "The reviewed record shows municipal, legislative, and statewide service across three sourced intervals. The election series contains three past contests on a shared vote-share scale. Policy characterization remains incomplete and is not inferred from the career record.",
    status: "ai-assisted-draft",
    disclosure: "AI-assisted draft generated from the cited fixture records; not a voting recommendation.",
    method: "The synthesis may restate sourced dates and coverage gaps but may not infer ideology or performance.",
    reviewStatus: "Unreviewed draft",
    generatedAt: "2026-08-24",
    sourceIds: ["official-biography", "legislative-directory", "election-results"],
    limitations: ["This fixture intentionally contains no policy-position analysis."],
  },
  sources: [
    {
      id: "official-biography",
      label: "Official biography fixture",
      publisher: "Example government office",
      kind: "official-government",
      url: "https://example.test/office/biography",
      checkedAt: "2026-08-24",
    },
    {
      id: "legislative-directory",
      label: "Legislative directory fixture",
      publisher: "Example legislature",
      kind: "legislative-record",
      url: "https://example.test/legislature/member",
      checkedAt: "2026-08-24",
    },
    {
      id: "election-results",
      label: "Official election-results fixture",
      publisher: "Example election authority",
      kind: "official-election",
      url: "https://example.test/elections/results",
      checkedAt: "2026-08-24",
    },
    {
      id: "campaign-profile",
      label: "Campaign profile fixture",
      publisher: "Candidate committee",
      kind: "campaign-controlled",
      url: "https://example.test/campaign/about",
      checkedAt: "2026-08-24",
    },
  ],
  limitations: [
    "This is a fictional development fixture, not a real candidate profile.",
    "Past election results describe different electorates and are not a forecast.",
    "Profile coverage does not measure performance or candidate quality.",
  ],
};

export const emptyProfileFixture = {
  checkedAt: "2026-08-24",
  photo: null,
  links: [],
  facts: [],
  timeline: [],
  elections: [],
  evidence: [],
  sources: [],
  limitations: ["Profile enrichment has not started."],
};
